### ISSUE TITLE
Add extension to Supabase

### ISSUE THREAD

**Issue by cilex-ft** [tvondra/sequential-uuids#10]
I've read [this issue](https://github.com/tvondra/sequential-uuids/issues/9) about _not_ adding this function to the core, and it makes sense; I'm embarking on on project on Supabase and I'd love to see this extension [available here](https://supabase.com/docs/guides/database/extensions).
Thank you for considering!

**Comment by tvondra** [comment]
That's really up to supabase - they can add include this extension if they choose to.
